title: Chris J Mears
email: chris@chrisjmears.com
url: https://chrisjmears.com
description: I help non-technical solo business owners take control of their web technology and get back to their passion.

footer:
  copyright: Wandering Leaf Studios, LLC

social:
  - title: twitter
    url: https://twitter.com/chrisjm
  - title: linkedin
    url: https://linkedin.com/in/chrisjm80
  - title: github
    url: https://github.com/chrisjm

plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
sass:
  style: :compressed

defaults:
  -
    scope:
      path: "_posts"
      type: posts
    values:
      is_post: true
