title: Chris J Mears
email: chris@chrisjmears.com
url: https://chrisjmears.com
description: I help non-technical small business owners take control of their web technology and get back to their passion.

footer:
  copyright: Wandering Leaf Studios, LLC

social:
  - title: twitter
    url: https://twitter.com/chrisjm
  - title: linkedin
    url: https://linkedin.com/in/chrisjm80
  - title: github
    url: https://github.com/chrisjm

og_image: "https://res.cloudinary.com/wanderingleafstudios/image/upload/v1537458385/chrisjmears.com/cjm-opengraph-20181019.jpg"

plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Build settings
markdown: kramdown
permalink: /blog/:title/
sass:
  style: :compressed

# Pagination settings
paginate: 5
paginate_path: "/blog/page-:num/"

defaults:
  -
    scope:
      path: "_posts"
      type: posts
    values:
      is_post: true
      comments: true
