# Site settings
title: Chris J Mears
email: chris@chrisjmears.com
url: http://chrisjmears.com
description: I help creative teams and entrepreneurs with all things tech.
description_html: I help creative teams and entrepreneurs with all things tech.

collections:
  - portfolio

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 93af6d #18bc9c #80B3FF
  secondary: 4298b5 #2c3e50 #FD6E8A
  secondary-dark: db5f39 #233140 #A2122F

# Footer settings
footer:
  copyright: Wandering Leaf Studios, LLC
  location: Location
  social: Around the Web
  credits: Colophon

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/chrisjm
  - title: linkedin
    url: http://linkedin.com/in/chrisjm80
  - title: github
    url: http://github.com/chrisjm

# Postal address (add as many lines as necessary)
address:
  - line: San Diego, CA

# Credits content
credits: 'Built with <a href="http://www.jekyllrb.com/">Jekyll</a>.<br>Design inspired by the <a href="http://jeromelachaud.github.io/freelancer-theme/">Freelancer theme</a>.'

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
sass:
  style: :compressed
