title: Chris J Mears
email: chris@chrisjmears.com
url: https://chrisjmears.com
description: I help solopreneurs take control of their web technology so they can stop worrying and get back to business.

footer:
  copyright: Wandering Leaf Studios, LLC

social:
  - title: twitter
    url: https://twitter.com/chrisjm
  - title: linkedin
    url: https://linkedin.com/in/chrisjm80
  - title: github
    url: https://github.com/chrisjm

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
sass:
  style: :compressed

defaults:
  -
    scope:
      path: "_posts"
      type: posts
    values:
      is_post: true
